version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run: pipenv run pip install git+https://github.com/o2r-project/mkdocs-combine.git#egg=mkdocs-combine
      - run:
          command: sudo apt-get install -y pandoc
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: generate docs
          command: pipenv run mkdocs build --clean --strict --verbose
      - run:
          command: pipenv run mkdocscombine --no-titles -o mydocs.pd
      - run:
          command: pandoc --toc -f markdown+grid_tables+table_captions -o site/specification.pdf mydocs.pd
      - store_artifacts:
          path: site
