version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: |
            sudo apt-get install build-essential python3-dev python3-pip \
                                 python3-setuptools python3-wheel python3-cffi \
                                 libcairo2 libpango-1.0-0 libpangocairo-1.0-0 \
                                 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: generate docs
          command: pipenv run mkdocs build --clean --strict --verbose
      - store_artifacts:
          path: site
